# Generated by Django 3.0.8 on 2020-08-16 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 16, 20, 20, 647170), editable=False),
        ),
    ]
