# Generated by Django 3.0.8 on 2020-08-16 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200816_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 16, 29, 1, 686305), editable=False),
        ),
    ]
